os:
  - linux
  - osx
  - windows
language: rust
rust:
  - 1.34.2
script:
  - cargo build --no-default-features --verbose --all
  - cargo test --no-default-features --verbose --all
  - cargo build --all-features --verbose --all
  - cargo test --all-features --verbose --all
  - ./test.sh

